name: 'Publish package'
description: ''
author: ''
inputs:
  tag:
    required: true
    description: 'github.ref'
    default: ''
  token:
    required: true
    description: 'NPM token'
    default: ''
runs:
  using: 'node12'
  main: 'lib/index.js'
